### Get Video Info - Success
POST http://127.00.0.1:9000/api/v1/youtube/info
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=jNQXAC9IVRw"
}

### Get Video Info - Invalid URL
POST http://127.0.0.1:9000/api/v1/youtube/info
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=invalidurlxyz"
}

### Download Video - Success
POST http://127.0.0.1:9000/api/v1/youtube/download
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=jNQXAC9IVRw"
}

### Download Video - Invalid URL
POST http://127.0.0.1:9000/api/v1/youtube/download
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=invalidurlxyz"
}

### Upload Bilibili Video - Success
POST http://localhost:9000/api/v1/bilibili/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="Me at the zoo.mp4"
Content-Type: video/mp4

< /mnt/d/temp/youtube-download/file_upload/Me at the zoo.mp4
--WebAppBoundary
Content-Disposition: form-data; name="cover_file"; filename="Me at the zoo.jpg"
Content-Type: image/jpeg

< /mnt/d/temp/youtube-download/file_upload/Me at the zoo.jpg
--WebAppBoundary
Content-Disposition: form-data; name="metadata_json"
Content-Type: application/json

{
    "tid": 17,
    "title": "我的B站首秀 - 动物园趣事",
    "tags": ["生活", "Vlog", "动物园"],
    "desc": "大家好，这是我在动物园拍摄的一些有趣片段，希望大家喜欢！",
    "pages": [
        {"title": "我的第一个B站视频 - Part 1", "description": "这是我上传的第一个B站视频片段描述。"}
    ]
}
--WebAppBoundary--